name: Upload to COS

on:
  push:
    branches:
      - main

jobs:
  UploadCOS:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies      
      run: npm install
    - name: Build      
      run: npm build
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SecretId }}
        SECRET_KEY: ${{ secrets.SecretKey }}
        BUCKET: deploy-1251567719/
        REGION: ap-beijing
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Delete current
      run: coscmd delete -rf /wesug-website/current
    - name: Upload
      run: coscmd upload -r ./dist/ /wesug-website/current
